### ISSUE TITLE
Can't get the similar scores for the readme images.

### ISSUE THREAD

**Issue by aijianiula0601** [titu1994/neural-image-assessment#11]
Thanks for your jobs!
I download the model in 'Releases Tab' and test the predict score for the images in your README.md,but can not get the similar scores. The inception_resnet and mobilenet have the same problem. why?

**Comment by titu1994** [comment]
Similar scores for which image?

**Comment by aijianiula0601** [comment]
The pictures locate in Example on your README.md page.

**Comment by titu1994** [comment]
These aren't the full scale images, so perhaps that's the reason for the score difference. I ram them at full size on the MobileNet model before it was updated.
