### ISSUE TITLE
How to use faeture in feature_generator?

### ISSUE THREAD

**Issue by Arieszhang1994** [titu1994/neural-image-assessment#12]
Hi titu1994,
I have just run your 3-step code and when I try to run pretrain_*.py
I got this problem.
`Traceback (most recent call last):
  File "pretrain_inception_resnet.py", line 82, in <module>
    model.fit_generator(features_generator(TRAIN_RECORD_PATH, batchsize=batchsize, shuffle=True),
TypeError: features_generator() missing 1 required positional argument: 'faeture_size'`
I knew it is because you didn't set feature in  pretrain_*.py
But I just can't figure out what does the faeture mean?

**Comment by titu1994** [comment]
I forgot to update the script. Feature size is the number of features from the final layer of the model, prior to classification. 

As such, it is specific to the model itself. Such that MobileNet has 1024 final features, NASNet has 1152 features. I forgot how many features inception ResNet V2 has, so you'll have to check that out and supply it as the second argument in the features generator
