### ISSUE TITLE
Not able to load utils,need extra setting？

### ISSUE THREAD

**Issue by butterl** [titu1994/neural-image-assessment#17]
Hi ， 

I tried with below inputs and get error outputs that functions in utils not found
```
~/code/ML/neural-image-assessment-0.5$ python3 evaluate_nasnet.py -dir ./inputs/ -resize true
Using TensorFlow backend.
Traceback (most recent call last):
  File "evaluate_nasnet.py", line 8, in <module>
    from utils.nasnet import NASNetMobile, preprocess_input
ImportError: No module named 'utils.nasnet'
```

do I need add below code to each script or I miss some settings?
```
import sys    
sys.path.append(path To Folder Containing Scripts) 
```

edit： using the 0.5 release version

**Comment by titu1994** [comment]
That shouldn't be required, but try with that? I haven't tried these scripts with Python 2.7

**Comment by butterl** [comment]
it's strange , tried python 2.7 and 3.5
add below split utils. from the import  and change Path to use os.patch solve my problem
```
import sys
sys.path.append("./utils")
```

**Comment by titu1994** [comment]
Interesting. I generally use an IDE like PyCharm so I don't encounter this issue. Anyway, glad it is resolved.

**Comment by butterl** [comment]
previous  tried 0.5 version and the HEAD of git also meet same problem, not sure if I got something wrong in my env， I modified the code and it could run mobilenet now :+1:
