### ISSUE TITLE
failed at the last step when I train nasnet 

### ISSUE THREAD

**Issue by kingrain213** [titu1994/neural-image-assessment#25]
When I run "python train_nasnet_mobile.py", It failed as follows:

1250/1250 [==============================] - 1439s 1s/step - loss: 0.0667 - val_loss: 0.0653
Exception IndexError: IndexError('list index out of range',) in <generator object val_generator at 0x24cf7c30> ignored
Exception IndexError: 'list index out of range' in <generator object get_controller at 0xd611500> ignored
Exception IndexError: IndexError('list index out of range',) in <generator object train_generator at 0x24cf7be0> ignored
Exception IndexError: 'list index out of range' in <generator object get_controller at 0xd611730> ignored

1)I didnt find anywhere a list index out of range.
2)I didnt find any file contains the Intermediate results,did you save the model that trained every epoch?
thks very much

**Comment by ranjiewwen** [comment]
when i run "evaluate_mobilenet.py" , i meet problem:

Traceback (most recent call last):
  File "H:/neural-image-assessment/evaluate_mobilenet.py", line 3, in <module>
    from path import Path
ImportError: No module named 'path'

anyone else meet this problem? the mode path where?

**Comment by titu1994** [comment]
What version of python are you using? This requires python 3.5.

**Comment by titu1994** [comment]
And as for the list index exception, are you trying a different dataset like TID2013? Then you will need to change the parameters of the data generators.

**Comment by ranjiewwen** [comment]
@titu1994  i am use "Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 17:44:09)  Windows10+tensorflow1.4"

**Comment by ranjiewwen** [comment]
i have solve this problem : https://pypi.org/project/path.py/ ;
use this ` pip install path.py `
