### ISSUE TITLE
Can you share a well-trained model or settings?

### ISSUE THREAD

**Issue by ken-ouyang** [titu1994/neural-image-assessment#30]
Hi, 

I'm using this code on AVA dataset  and have encountered some problem when training.  The model converges at around 10th epoch but the prediction result is not as expected. The score of all pictures are around 5.x and also the model can not figure out which picture is better. I'm using the directly training method and have tried mobilenet / vgg16 / resnet50 / inceptionv3 but none of them works. 

So could you please share the exact settings for the one used in the demo images? Or can you share the well trained models ?  Many thanks.

**Comment by titu1994** [comment]
The trained models are available in the releases tab. However, I will not be able to train any model currently. 

It seems that it is necessary to fine-tune the entire model and not just the final few layers to improve performance.
