### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by jiazhenggod** [titu1994/neural-image-assessment#33]
Hello, how long does it take for you to train with 250000 images? I am training with a small sample of  1000 images, and each epoch is taking about 1 hour. Is this time normal I haven't done much machine learning before so I don't have a good concept of this. The machine i use have a good nvidia gpu. Do i need any adjustment or tensorflow can automatically find the gpu and use it? Currently i only installed tensorflow 1.4. thanks for the help!

**Comment by titu1994** [comment]
Make sure you use `pip install tensorflow-gpu` to use the GPU on your system. 

It takes me 1 hour for 1 epoch, and most of these models are treined for 15 epochs.
