### ISSUE TITLE
CoreML model input type is MultiArray instead of Image

### ISSUE THREAD

**Issue by keithZumper** [titu1994/neural-image-assessment#34]
I was able to successfully save the MobileNet NIMA model as a coreML model however the input is not what I was expecting. It shows the input as MultiArray instead of an Image
```
base_model = MobileNet((None, None, 3), alpha=1, include_top=False, pooling='avg', weights=None)
x = Dropout(0.75)(base_model.output)
x = Dense(10, activation='softmax')(x)

model = Model(base_model.input, x)
model.load_weights('weights/mobilenet_weights.h5')
coreml_model = coremltools.converters.keras.convert(model)
coreml_model.save("mobilenet_nima2.mlmodel")
```

CoreML metaData
<img width="317" alt="screen shot 2018-06-25 at 7 17 43 pm" src="https://user-images.githubusercontent.com/25964151/41932325-91b5ecd8-7935-11e8-8636-5359377583b2.png">

Ideally what the input and output should resemble:
<img width="341" alt="screen shot 2018-06-25 at 7 17 40 pm" src="https://user-images.githubusercontent.com/25964151/41932329-95700836-7935-11e8-8a74-ad8631db2fa7.png">

I also tried converting the model by passing in an image_input_names parameter
```
coreml_model = coremltools.converters.keras.convert(model, image_input_names='img', input_names='img')
```
but I received an unpack error from the coreML builder tools
```
/coremltools/models/neural_network/builder.py", line 2547, in set_pre_processing_parameters
    channels, height, width = array_shape
ValueError: need more than 1 value to unpack
```

Code where the error originates
https://github.com/apple/coremltools/blob/master/coremltools/models/neural_network.py
```
        # Add image inputs
        for input_ in spec.description.input:
            if input_.name in image_input_names:
                if input_.type.WhichOneof('Type') == 'multiArrayType':
                    array_shape = tuple(input_.type.multiArrayType.shape)
                    channels, height, width = array_shape
```

Any idea why the keras model is converting to a CoreML model with input MultiArray type instead of an image?

There have been MobileNet models that have been successfully converted to a CoreML model with image as an input e.g. https://github.com/hollance/MobileNet-CoreML

**Comment by titu1994** [comment]
Instead of using None, None, 3 as the input shape, use a static size such as 224.

**Comment by keithZumper** [comment]
Worked! Thanks @titu1994
