### ISSUE TITLE
Can not get the same weights file as in the release

### ISSUE THREAD

**Issue by ziibinj** [titu1994/neural-image-assessment#38]
Hi titu, thanks for your work!
I run the training code you wrote and the generated weight file looks quite different with file posted in the release. I run a test with some images using the weight file I got and the release weight file, and find almost every image got different scores with these two weight file.
How does this happen?

**Comment by titu1994** [comment]
Training is not deterministic, so some times it happens. Did the scores vary drastically?

**Comment by ziibinj** [comment]
Yes, it vary drastically. Compare to the scores got by weights file in the release, some low quality images got high score while some high quality images got low score, the scores' difference even greater than 1.

**Comment by ziibinj** [comment]
As the inception_resnet_v2 weights file, an obvious difference is that the release weights file has 219071424 bytes, while the trained result of mine has 219071744 bytes, don't know what cause this difference.

**Comment by titu1994** [comment]
300 bytes aren't what I'd call significant. I think you require further training. All the models were trained for well over 20-25 epochs, and this was training the entire network, not just the final kauersc

**Comment by ziibinj** [comment]
I got it. I read your discussion with tfriedel, tried his way and get a result weights file similar to the release. Firstly train the FC layer and the train the entire network.

**Comment by titu1994** [comment]
Yes, without fine-tuning all of the layers, it doesn't get great results.
