### ISSUE TITLE
for trainable params

### ISSUE THREAD

**Issue by jiazhenggod** [titu1994/neural-image-assessment#41]
Total params: 4,280,286
Trainable params: 10,570
Non-trainable params: 4,269,716

this is what i got, i tried different dataset but it's always like this. Is this normal?Or any cause for so many non-trainable params? Also do the training images also need to be resized to 224*224 before training? Thanks.

**Comment by titu1994** [comment]
If you are training only the last layer, then yes. That is the number of params of the final dense layer. 

Yes, images need to be scaled to 224,224
