### ISSUE TITLE
Hello author, why did I run the first epoch without a problem, and the second epoch program crashed.

### ISSUE THREAD

**Issue by ubantu3** [titu1994/neural-image-assessment#45]
Hello author, why did I run the first epoch without a problem, and the second epoch program [crashed.[]
![_15372715086205](https://user-images.githubusercontent.com/18569289/45878160-ab542380-bdd2-11e8-8d9b-417061e5db33.png)
)

**Comment by titu1994** [comment]
Inside utils folder, there is a check_dataset.py script. Copy paste that inside the AVA dataset folder and run it. It will print out a list of files that are corrupted. Delete those files. 

The issue is caused due to those corrupted JPEG files.
