### ISSUE TITLE
Weight freezing in train*.py

### ISSUE THREAD

**Issue by erensezener** [titu1994/neural-image-assessment#49]
I see that the weights besides the very top layer are frozen in `train*.py` files:

```
base_model = InceptionResNetV2(input_shape=(image_size, image_size, 3), include_top=False, pooling='avg')
for layer in base_model.layers:
    layer.trainable = False
```

Are the weights provided in the releases page also obtain this way?

**Comment by titu1994** [comment]
The weights for everything other than MobileNet in the releases page were trained using both freezing and training + full model fine-tuning. 

Those are donated by others who also had an interest in the repository.

**Comment by erensezener** [comment]
Thanks a lot. Issue closed.
