### ISSUE TITLE
Can i train ava with inception_v3?

### ISSUE THREAD

**Issue by aijianiula0601** [titu1994/neural-image-assessment#5]
Thanks for job!
I read your codes. you train ava dataset wich mobiblenet,but I think this model design for mobile and its accuracy is not as good as inception_v3. Since this is a classification task, it can also train wich inception_v3. How do you think?

**Comment by tfriedel** [comment]
Yes you can definitely do this. I trained on inception resnet v2 and got better results (loss 0.070). I will upload the model soon.
