### ISSUE TITLE
parse data function-image augmentation

### ISSUE THREAD

**Issue by ranju2015** [titu1994/neural-image-assessment#57]
I have just copied the following first four lines from parse_data function in utils/data_loader.py

image = tf.read_file(filename)
image = tf.image.decode_jpeg(image, channels=3)
image = tf.image.resize_images(image, (256, 256))
image = tf.random_crop(image, size=(IMAGE_SIZE, IMAGE_SIZE, 3))

If my image IMAGE_SIZE is 331x331, how this crop statement is going to work. Is it ok to set the IMAZE_SIZE variable to 331 or do I need to change the resize image parameter? Please suggest.

**Comment by titu1994** [comment]
If you'd like 331x331 image size then change the tuple (256,256) to (331,331)

**Comment by ranju2015** [comment]
Many thanks for your quick reply. 

I wanted to try NasNetLarge. The default input_shape=(331, 331, 3). 
howerver,  before call NasNetLarge image size is set to 224.

image_size = 224

base_model = NasNetLarge((image_size, image_size, 3), include_top=False, pooling='avg', weight_decay=0, dropout=0)

My question was, do I need to resize the image to 331x331 to obtain the full potential of NasNetLarge?

**Comment by titu1994** [comment]
Yes nasnet large requires 331x331

**Comment by ranju2015** [comment]
Okay. thanks.
