### ISSUE TITLE
Theano backend

### ISSUE THREAD

**Issue by arianaa30** [titu1994/neural-image-assessment#60]
Is it pre-configured to use Theano backend?! When I run it, it says `Using Theano backend.`. My local configs are all on Tensorflow though.

**Comment by titu1994** [comment]
No. It only supports tensorflow.

**Comment by arianaa30** [comment]
Yeah weird! :-/

**Comment by arianaa30** [comment]
Ah got it...no worries:
`Using TensorFlow backend.`
