### ISSUE TITLE
nasnet weights incorrectly loaded

### ISSUE THREAD

**Issue by tfriedel** [titu1994/neural-image-assessment#8]
So, I was just refactoring my fork of the code and I got bad results in the nasnet evaluation script.
It turns out there's a bug when loading the weights.

`model.load_weights('weights/nasnet_weights.h5', by_name=True)`

Remove by_name=true! Most layers have names generated on the fly, except maybe the fully connected layer. So what this does is probably only loading the fully connected layer's weights!
If you load the complete network, you will get good results!

**Comment by titu1994** [comment]
I removed that line in the latest commit, but the scores do not change from the previous discussion

Evaluating :  images/art1.jpg
NIMA Score : 5.988 +- (1.575)

Evaluating :  images/art2.jpg
NIMA Score : 4.268 +- (1.694)

Evaluating :  images/art3.jpg
NIMA Score : 4.655 +- (1.521)

Evaluating :  images/art4.jpg
NIMA Score : 5.558 +- (1.510)

Evaluating :  images/art5.jpg
NIMA Score : 6.123 +- (1.574)

Evaluating :  images/art6.jpg
NIMA Score : 6.596 +- (1.607)

This is after resizing images to 224x224 directly. I will try your resize script from the drive folder to see if it makes much of a difference

**Comment by titu1994** [comment]
With the resize script from your drive, these are the following scores 

Evaluating :  images/art1.jpg
NIMA Score : 5.710 +- (1.470)

Evaluating :  images/art2.jpg
NIMA Score : 5.623 +- (1.440)

Evaluating :  images/art3.jpg
NIMA Score : 5.365 +- (1.346)

Evaluating :  images/art4.jpg
NIMA Score : 5.591 +- (1.512)

Evaluating :  images/art5.jpg
NIMA Score : 6.244 +- (1.549)

Evaluating :  images/art6.jpg
NIMA Score : 6.037 +- (1.561)

These scores are even more scattershot than before. Obviously, the art pieces are very highly influenced by their aspect ratio when resizing, cropping or any other operation, causing large fluctuations in their scores.

**Comment by tfriedel** [comment]
You need to choose some images which have more similarity to the training set.
I did write a script which sorts images in lightroom according to the scores and used in on some personal folders, holiday images etc. 
It did an okay job, but not really good enough in my opinion. Okay the images with bad scores were always bad, like blurry or accidental photos. Some of the highest rated images were kind of abstract and had repetitive elements. 
I had one folder with lots of random images, like even screenshots from google maps for example. And they were rated rather highly ^^
But no wonder, those kind of images were not in the training so it had no idea what to do with them. 
I guess this is a problem when you only consider images which were submitted to photo contests. A better training set in this case would include typical images people have on their phones.

**Comment by titu1994** [comment]
That seems to be the case.
